In [1]:
import pandas
import sqlite3
import numpy

In [2]:
conn = sqlite3.connect('/home/computerowner/Documents/PythonCodes/Bets/BettingData.db')
dfSeason = pandas.read_sql_query('SELECT * FROM SeasonResults', conn)
dfGame = pandas.read_sql_query('SELECT * FROM GameResults', conn)

dfSeason['PointsFor'] = pandas.to_numeric(dfSeason['PointsFor'])

In [3]:
lastSeason = dfSeason.copy()

In [4]:
uniqueSchoolNames = dfSeason.SchoolName.unique()
# print (uniqueSchoolNames)
uniqueYears = dfSeason.Year.unique()
# print (uniqueYears)
# uniqueYears.dtype

In [5]:
yearList = list()
schoolList = list()
meanList = list()
medianList = list()
stdevList = list()
countList = list()

myDict = {}

for school in uniqueSchoolNames:
    for year in uniqueYears:
        thatYear = year
        yearList.append(year)
#         print (year)
        someSchool = lastSeason[(lastSeason['SchoolName'] == school) & (lastSeason['Year'] == year)].copy()
#         print (someSchool)
        schoolList.append(school)
#         print (school)
        mean = someSchool['PointsFor'].mean()
        meanList.append(mean)
#         print (mean)
        median = someSchool['PointsFor'].median()
        medianList.append(median)
#         print (median)
        stdev = someSchool['PointsFor'].std()
        stdevList.append(stdev)
#         print (stdev)
        count = len(someSchool.index)
        countList.append(count)
#         print (count)

myDict = {'year': yearList, 'schoolName':schoolList, 'mean':meanList, 'median':medianList, 'stdev':stdevList, 'count': countList} 
schoolStats = pandas.DataFrame(myDict)
schoolStats.dropna()
schoolStats

      count       mean  median        schoolName      stdev  year
0        12  23.250000    20.5         air-force  10.471824  2006
1        13  29.923077    31.0         air-force  12.912923  2007
2        13  26.769231    27.0         air-force   8.506408  2008
3        13  29.692308    26.0         air-force  17.810973  2009
4        13  30.846154    25.0         air-force  16.697536  2010
5        13  34.923077    35.0         air-force  12.658736  2011
6        13  27.384615    25.0         air-force  12.790221  2012
7        12  24.666667    20.5         air-force  11.979781  2013
8        13  31.461538    30.0         air-force  12.692618  2014
9        14  33.785714    35.0         air-force  14.219048  2015
10       12  19.666667    20.0             akron  10.342616  2006
11       12  21.166667    21.0             akron  14.351644  2007
12       12  30.000000    31.5             akron  13.142575  2008
13       12  19.250000    18.5             akron   9.799119  2009
14       12  15.583333    14.0             akron  10.569754  2010
15       12  14.166667    15.5             akron  10.760478  2011
16       12  26.083333    23.5             akron  17.422338  2012
17       12  20.166667    22.0             akron   9.721890  2013
18       12  22.583333    22.5             akron   9.976867  2014
19       13  23.923077    20.0             akron  16.800107  2015
20       13  22.923077    23.0           alabama   9.869663  2006
21       13  27.076923    27.0           alabama  12.783202  2007
22       14  30.142857    30.5           alabama   9.875043  2008
23       14  32.071429    33.0           alabama  10.716373  2009
24       13  35.692308    30.0           alabama  15.250053  2010
25       13  34.846154    38.0           alabama  12.542236  2011
26       14  38.714286    40.5           alabama   9.059025  2012
27       13  38.153846    38.0           alabama  10.550246  2013
28       14  36.928571    38.0           alabama  14.171826  2014
29       15  35.066667    35.0           alabama   8.606199  2015
...     ...        ...     ...               ...        ...   ...
1250     13  23.000000    20.0  western-michigan   9.823441  2006
1251     12  26.916667    25.5  western-michigan  12.859085  2007
1252     13  28.615385    28.0  western-michigan  11.629979  2008
1253     12  24.666667    21.0  western-michigan  16.383658  2009
1254     12  32.333333    31.0  western-michigan  14.871164  2010
1255     13  35.307692    38.0  western-michigan  18.130934  2011
1256     12  29.333333    24.0  western-michigan  13.573593  2012
1257     12  17.166667    17.0  western-michigan   9.580599  2013
1258     13  33.769231    34.0  western-michigan  11.395568  2014
1259     13  36.000000    35.0  western-michigan  15.253415  2015
1260     13  29.230769    30.0         wisconsin  13.109499  2006
1261     13  29.461538    33.0         wisconsin  12.718853  2007
1262     13  27.461538    25.0         wisconsin  14.858305  2008
1263     13  31.769231    31.0         wisconsin  12.063401  2009
1264     13  41.461538    34.0         wisconsin  20.718813  2010
1265     14  44.142857    43.5         wisconsin  11.230844  2011
1266     14  29.571429    26.5         wisconsin  18.462912  2012
1267     13  34.846154    30.0         wisconsin  11.998932  2013
1268     14  34.571429    34.0         wisconsin  17.328120  2014
1269     13  26.769231    24.0         wisconsin  14.219434  2015
1270     12  21.500000    24.0           wyoming  11.866684  2006
1271     12  19.416667    23.5           wyoming  11.325421  2007
1272     12  12.666667    13.5           wyoming  10.111500  2008
1273     13  18.307692    17.0           wyoming  14.043887  2009
1274     12  19.166667    18.0           wyoming  13.782950  2010
1275     13  26.076923    25.0           wyoming  10.095061  2011
1276     12  26.833333    28.0           wyoming   9.417907  2012
1277     12  31.250000    34.5           wyoming  17.955121  2013
1278     12  21.083333    18.5           wyoming  10.916696  2014
1279     12  19.000000    15.5           wyoming  10.036298  2015

[1280 rows x 6 columns]